.\" Man page for SimplePictureTool
.\" Contact: patrice.coni-dev@yandex.com
.TH SimplePictureTool 1 "November  20 2022"
.SH NAME
SimplePictureTool \- Batch progressing of picture files
.SH SYNOPSIS
SimplePictureTool is a utility for batch progressing of picture files based on Qt and C++.
.SH DESCRIPTION
SimplePictureTool is a simple tool for batch processing 
of .PNG or .JPG image files in a simple way.
It allows removing metadata from image files and scaling 
the image size and adjusting the image quality 
using ImageMagick.
.SH OPTIONS
No options for this man pages.
.SH SEE ALSO
man(1), groff(1), man.config(5)
.SH BUGS
If you find a bug, please report it at below E-Mail-address.
.SH AUTHOR
Patrice Coni (patrice.coni-dev@yandex.com)
